site_name: hyper-bump-it Documentation
site_url: https://plannigan.github.io/hyper-bump-it/
repo_url: https://github.com/plannigan/hyper-bump-it
repo_name: plannigan/hyper-bump-it
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Usage Guide:
    - Configuration: usage-guide/configuration.md
    - Format Patterns: usage-guide/format-patterns.md
    - Git Integration: usage-guide/git-integration.md
  - Why hyper-bump-it?: why-hyper-bump-it.md
  - Changelog: changelog.md
theme:
  name: material
  custom_dir: docs/.theme-overrides
  features:
    - content.tabs.link
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
extra:
  version:
    provider: mike
    default: latest
extra_css:
  - css/mkdocstrings.css
